declare module 'vue' {
  export interface GlobalComponents {
    PaContainer: typeof import('../src/packages/components/container/container.vue')['default']
    PaCell: typeof import('../src/packages/components/cell/cell.vue')['default']
    PaCellGroup: typeof import('../src/packages/components/cell-group/cell-group.vue')['default']
    PaButton: typeof import('../src/packages/components/button/button.vue')['default']
    PaBottomPopup: typeof import('../src/packages/components/bottom-popup/bottom-popup.vue')['default']
    PaCascader: typeof import('../src/packages/components/cascader/cascader.vue')['default']
    PaCheckboxBtns: typeof import('../src/packages/components/checkbox-btns/checkbox-btns.vue')['default']
    PaField: typeof import('../src/packages/components/field/field.vue')['default']
    PaForm: typeof import('../src/packages/components/form/form.vue')['default']
    PaFormItem: typeof import('../src/packages/components/form-item/form-item.vue')['default']
    PaIcon: typeof import('../src/packages/components/icon/icon.vue')['default']
    PaList: typeof import('../src/packages/components/list/list.vue')['default']
    PaLoadmore: typeof import('../src/packages/components/loadmore/loadmore.vue')['default']
    PaNavBar: typeof import('../src/packages/components/nav-bar/nav-bar.vue')['default']
    PaPickerPopup: typeof import('../src/packages/components/picker-popup/picker-popup.vue')['default']
    PaPickerView: typeof import('../src/packages/components/picker-view/picker-view.vue')['default']
    PaPopover: typeof import('../src/packages/components/popover/popover.vue')['default']
    PaSafeBottom: typeof import('../src/packages/components/safe-bottom/safe-bottom.vue')['default']
    PaSearch: typeof import('../src/packages/components/search/search.vue')['default']
    PaSortLabel: typeof import('../src/packages/components/sort-label/sort-label.vue')['default']
    PaSticky: typeof import('../src/packages/components/sticky/sticky.vue')['default']
    PaTabs: typeof import('../src/packages/components/tabs/tabs.vue')['default']
    PaTabPane: typeof import('../src/packages/components/tab-pane/tab-pane.vue')['default']
    PaTooltip: typeof import('../src/packages/components/tooltip/tooltip.vue')['default']
    PaWatermark: typeof import('../src/packages/components/watermark/watermark.vue')['default']
    PaPopup: typeof import('../src/packages/components/popup/popup.vue')['default']
    PaSection: typeof import('../src/packages/components/section/section.vue')['default']
    PaBadge: typeof import('../src/packages/components/badge/badge.vue')['default']
    PaSteps: typeof import('../src/packages/components/steps/steps.vue')['default']
    PaSwitch: typeof import('../src/packages/components/switch/switch.vue')['default']
    PaTag: typeof import('../src/packages/components/tag/tag.vue')['default']
    PaTransition: typeof import('../src/packages/components/transition/transition.vue')['default']
    PaInputNumber: typeof import('../src/packages/components/input-number/input-number.vue')['default']
    PaTextarea: typeof import('../src/packages/components/textarea/textarea.vue')['default']
    PaImage: typeof import('../src/packages/components/image/image.vue')['default']
    PaLoadingIcon: typeof import('../src/packages/components/loading-icon/loading-icon.vue')['default']
    PaRadio: typeof import('../src/packages/components/radio/radio.vue')['default']
    PaRadioGroup: typeof import('../src/packages/components/radio-group/radio-group.vue')['default']
    PaSwipeCell: typeof import('../src/packages/components/swipe-cell/swipe-cell.vue')['default']
    PaCheckbox: typeof import('../src/packages/components/checkbox/checkbox.vue')['default']
    PaCheckboxGroup: typeof import('../src/packages/components/checkbox-group/checkbox-group.vue')['default']
    PaCalendar: typeof import('../src/packages/components/calendar/calendar.vue')['default']
    PaCountTo: typeof import('../src/packages/components/count-to/count-to.vue')['default']
    PaEmpty: typeof import('../src/packages/components/empty/empty.vue')['default']
    PaOverlay: typeof import('../src/packages/components/overlay/overlay.vue')['default']
    PaMenu: typeof import('../src/packages/components/menu/menu.vue')['default']
    PaMenuItem: typeof import('../src/packages/components/menu-item/menu-item.vue')['default']
    PaSidebar: typeof import('../src/packages/components/sidebar/sidebar.vue')['default']
    PaSidebarItem: typeof import('../src/packages/components/sidebar-item/sidebar-item.vue')['default']
    PaDatePicker: typeof import('../src/packages/components/date-picker/date-picker.vue')['default']
    PaCollapse: typeof import('../src/packages/components/collapse/collapse.vue')['default']
    PaCollapseItem: typeof import('../src/packages/components/collapse-item/collapse-item.vue')['default']
    PaSkeleton: typeof import('../src/packages/components/skeleton/skeleton.vue')['default']
    PaUploader: typeof import('../src/packages/components/uploader/uploader.vue')['default']
    PaIndexBar: typeof import('../src/packages/components/index-bar/index-bar.vue')['default']
    PaIndexAnchor: typeof import('../src/packages/components/index-anchor/index-anchor.vue')['default']
    PaTabbar: typeof import('../src/packages/components/tabbar/tabbar.vue')['default']
    PaTabbarItem: typeof import('../src/packages/components/tabbar-item/tabbar-item.vue')['default']
    PaNoticeBar: typeof import('../src/packages/components/notice-bar/notice-bar.vue')['default']
    PaDialog: typeof import('../src/packages/components/dialog/dialog.vue')['default']
    PaInput: typeof import('../src/packages/components/input/input.vue')['default']
  }
}

export {}
